service:
  flask-backend:
    build: ./config
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema.ddl:/docker-entrypoint-initdb.d/schema.ddl
    ports:
      - "5432:5432"
    networks:
      - default
  
  django:
    build: ./django_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_app.settings
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge